Patch 1
JMGaljaard/fltk-testbed pull request #57
Opened 2022-10-03 16:03 UTC by V0XNIHILI

Fix a few things that made it impossible to setup a cluster from scratch with the current commit on main.

2022-10-04 13:04 UTC, JMGaljaard requested changes
Please address the issues raised and/or open a github issue addressing issues that you have encountered

2022-10-04 13:04 UTC, JMGaljaard commented on terraform/terraform-dependencies/main.tf
> +  chart      = "${path.module}/../../charts/nfs-server-provisioner-1.3.1.tgz"
This seems to be related to an earlier patch that has been provided in #52. Please open an issue to the problem that you encountered to make discussion easier.

2022-10-05 14:01 UTC, V0XNIHILI commented on jupyter/terraform_notebook.ipynb
> +    "wget https://kvaps.github.io/charts/nfs-server-provisioner-1.3.1.tgz -O ../charts/nfs-server-provisioner-1.3.1.tgz"
Yes it is, as Helm does not do this (at least for my case and for my project group partner)

2022-10-05 14:01 UTC, V0XNIHILI commented on jupyter/terraform_notebook.ipynb
> +    "OWNER_MAIL=\"DouweDB@gmail.com\"\n",
Will do, thought I didn't commit this

2022-10-05 14:02 UTC, V0XNIHILI commented on configs/example_cloud_experiment.json
> +         "c": "batch"
Sorry, copy paste mistake, will fix it.

2022-10-05 14:14 UTC, JMGaljaard commented on terraform/terraform-dependencies/main.tf
> +  chart      = "${path.module}/../../charts/nfs-server-provisioner-1.3.1.tgz"
This has been addressed in #59

2022-10-06 07:19 UTC, JMGaljaard commented on jupyter/terraform_notebook.ipynb
> +    "wget https://kvaps.github.io/charts/nfs-server-provisioner-1.3.1.tgz -O ../charts/nfs-server-provisioner-1.3.1.tgz"
This has now been resolved in #58

2022-10-07 12:40 UTC, V0XNIHILI commented
I will close this PR as you fixed the main issue in #59.

2022-10-07 12:40 UTC, closed without merging